# Generated by Django 6.1.1 on 2026-09-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('raison_sociale', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('creating_db', 'Création de la base'), ('migrating', 'Migration'), ('seeding', 'Initialisation'), ('active', 'Actif'), ('failed', 'Échec'), ('suspended', 'Suspendu'), ('dropping', 'Suppression'), ('deleted', 'Supprimé')], db_index=True, default='pending', max_length=16)),
                ('db_name', models.CharField(blank=True, max_length=63, null=True, unique=True)),
                ('db_host', models.CharField(max_length=255)),
                ('db_port', models.PositiveIntegerField(default=6432)),
                ('db_user', models.CharField(blank=True, max_length=63, null=True)),
                ('db_password_encrypted', models.BinaryField(blank=True, null=True)),
                ('applied_heads', models.JSONField(blank=True, default=dict)),
                ('schema_digest', models.CharField(blank=True, max_length=64)),
                ('schema_checked_at', models.DateTimeField(blank=True, null=True)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'active'), _negated=True), ('db_name__isnull', False), _connector='OR'), name='active_client_has_db_name', violation_error_message='An ACTIVE client must have a db_name. A client with no database is not routable, and the router must never see one.')],
            },
        ),
    ]
