# Generated by Django 6.1.1 on 2026-09-13 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.CharField(default='command', help_text='command / celery / deploy — how this run was started.', max_length=64)),
                ('target_heads', models.JSONField(blank=True, default=dict)),
                ('mode', models.CharField(choices=[('apply', 'Application'), ('check', 'Vérification')], default='apply', max_length=8)),
                ('status', models.CharField(choices=[('running', 'En cours'), ('ok', 'Terminé'), ('failed', 'Échec')], default='running', max_length=8)),
                ('succeeded', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('behind', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'migration run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MigrationRunResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ok', 'À jour'), ('failed', 'Échec'), ('behind', 'En retard'), ('skipped', 'Ignoré')], max_length=8)),
                ('heads_before', models.JSONField(blank=True, default=dict)),
                ('heads_after', models.JSONField(blank=True, default=dict)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('error', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='control_plane.client')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='control_plane.migrationrun')),
            ],
            options={
                'verbose_name': 'migration run result',
                'ordering': ['client__code'],
                'indexes': [models.Index(fields=['run', 'status'], name='control_pla_run_id_08a3b0_idx')],
            },
        ),
    ]
