# Generated by Django 6.1.1 on 2026-09-13 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0002_migrationrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'En cours'), ('ok', 'Terminé'), ('failed', 'Échec')], default='running', max_length=8)),
                ('bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('object_key', models.CharField(blank=True, max_length=255)),
                ('schema_digest', models.CharField(blank=True, max_length=64)),
                ('error', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backups', to='control_plane.client')),
            ],
            options={
                'verbose_name': 'backup run',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['client', 'started_at'], name='control_pla_client__0d3c93_idx')],
            },
        ),
    ]
