/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/connexion/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ouvrir une session
         * @description `POST /api/auth/connexion/` — établit la session et renvoie l'amorçage complet.
         *
         *     **Protégée par CSRF bien qu'anonyme.** Les vues DRF sont `csrf_exempt` au niveau du
         *     middleware et `SessionAuthentication` n'impose le CSRF qu'aux utilisateurs déjà
         *     authentifiés : sans ce décorateur, la connexion serait la seule écriture non protégée
         *     du produit. Le login CSRF est une vraie attaque — on force une victime dans la session
         *     de l'attaquant, qui relit ensuite ce qu'elle y a saisi. La SPA appelle déjà
         *     `/api/auth/csrf/` au montage (`03-UI-SPEC.md` 6), donc cela ne lui coûte rien.
         *
         *     `login()` fait tourner la clé de session : la fixation de session est traitée par
         *     Django et **ne doit pas** être réimplémentée (menace T-03-50).
         */
        post: operations["auth_connexion_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/csrf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poser le cookie CSRF
         * @description Appelé par la SPA au montage de l'écran de connexion, avant le premier POST.
         */
        get: operations["auth_csrf_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/deconnexion/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fermer la session
         * @description `POST /api/auth/deconnexion/` — `logout()` vide la ligne de session.
         *
         *     Révocation réelle et immédiate : il n'y a aucune fenêtre d'expiration à attendre
         *     parce qu'il n'y a plus rien à expirer. C'est la moitié « révocation » de l'argument
         *     session-contre-jeton, et le test rejoue la clé après coup pour le prouver.
         */
        post: operations["auth_deconnexion_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/moi/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * L'amorçage de la SPA
         * @description `GET /api/auth/moi/` — tout l'amorçage de la SPA, en une requête.
         *
         *     Le compte, l'affaire, les entrées de navigation autorisées, les magasins accordés et
         *     le catalogue des droits. Une requête plutôt que cinq : c'est la première chose qui se
         *     passe après la connexion, et chaque aller-retour supplémentaire est une fraction de
         *     seconde d'écran vide au comptoir.
         */
        get: operations["auth_moi_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mot-de-passe/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Changer son mot de passe
         * @description `POST /api/auth/mot-de-passe/` — le changement par l'intéressé.
         *
         *     Efface `doit_changer_mot_de_passe`, ce qui libère la SPA de la route
         *     `/mot-de-passe` sur laquelle elle atterrit tant que le drapeau est vrai. Renvoie
         *     l'amorçage à jour, pour que l'interface n'ait pas à deviner l'état d'après un 200.
         */
        post: operations["auth_mot_de_passe_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chercher ou lister les clients
         * @description Liste de candidats classés. **Aucun appelant ne doit auto-sélectionner sur un nom.** Aucun seuil ne sépare « Mhamed ↔ Mohammed » (0,333) de « Fatima ↔ Fatiha » (0,571) : le classement est inversé, et un faux positif au comptoir ouvre la fiche du voisin — avec ses ordonnances, c'est une divulgation de donnée de santé, pas une gêne d'interface. `correspondance_exacte` ne se pose que sur un numéro de téléphone complet, jamais sur un nom.
         */
        get: operations["clients_list"];
        put?: never;
        /**
         * Créer une fiche client
         * @description La ressource client. **Deux absences délibérées, écrites ici pour être trouvées.**
         *
         *     ## 1. Le mixin de portée magasin est absent, et ce n'est pas un oubli
         *
         *     Un client appartient à l'**affaire**, pas à un point de vente : il achète à Anfa
         *     aujourd'hui et à Maârif dans six mois, et c'est la même personne (décision D-4a). Le
         *     scoper produirait deux fiches pour un humain, donc deux historiques de prescription
         *     pour un seul œil. **Le raisonnement complet, avec sa conséquence clinique, vit dans
         *     la docstring de `clients.Client`** (`domaine/clients/models.py`), qui dit aussi
         *     pourquoi la garde de `plateforme/projection/checks.py` est structurellement aveugle
         *     ici — elle ne se déclenche que sur un modèle scopé, donc elle ne dira ni qu'il manque
         *     une portée, ni qu'il n'en faut pas. La garde **positive** vit au plan 04-04, à côté
         *     de `Ordonnance`.
         *
         *     **Pourquoi ce paragraphe ne nomme pas le mixin.** Le plan 04-03 fait de son absence
         *     un critère grepable sur ce fichier ; l'y écrire rendrait le critère rouge sur le
         *     fichier même qui le respecte. C'est la même arbitrage qu'au plan 04-01 avec
         *     `unaccent`, et la même leçon : un critère qui attrape sa propre prose est un critère
         *     mal écrit — il devrait chercher une **ligne d'import** ou une **base de classe**, pas
         *     un mot. Noté pour `04-09`.
         *
         *     Conséquence à ne pas manquer : la portée des lignes de cette ressource est
         *     l'**affaire entière**, et c'est `client.voir` qui en garde la porte. Il n'y a rien à
         *     filtrer dans `get_queryset()` à ce titre.
         *
         *     ## 2. Pas de `DestroyModelMixin`, et `delete` absent de `http_method_names`
         *
         *     Une fiche client se **désactive** (`actif = False`). L'article 211 du CGI impose dix
         *     ans de conservation, et la phase 6 posera un `PROTECT` depuis la facture. `put` est
         *     absent pour la raison de `VueComptes` : un remplacement complet n'a aucun usage ici
         *     et offrirait une seconde porte d'écriture à tenir en cohérence avec la première.
         *
         *     ## 3. Aucun nouveau paramètre de requête, et c'est écrit pour que l'absence se lise
         *
         *     `search` figure **déjà** dans `PARAMETRES_RESERVES`
         *     (`plateforme/projection/filtres.py`), donc `?search=` n'y ajoute rien et le fichier
         *     n'est pas touché par ce plan. Tout autre nom — `?q=`, `?telephone=` — devrait y
         *     entrer **dans le même commit**, sans quoi il produirait le refus unique.
         *     `test_client01_tout_parametre_hors_liste_blanche_est_refuse` vérifie les trois noms
         *     que l'on écrit sans y penser.
         */
        post: operations["clients_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * La fiche d'un client
         * @description La ressource client. **Deux absences délibérées, écrites ici pour être trouvées.**
         *
         *     ## 1. Le mixin de portée magasin est absent, et ce n'est pas un oubli
         *
         *     Un client appartient à l'**affaire**, pas à un point de vente : il achète à Anfa
         *     aujourd'hui et à Maârif dans six mois, et c'est la même personne (décision D-4a). Le
         *     scoper produirait deux fiches pour un humain, donc deux historiques de prescription
         *     pour un seul œil. **Le raisonnement complet, avec sa conséquence clinique, vit dans
         *     la docstring de `clients.Client`** (`domaine/clients/models.py`), qui dit aussi
         *     pourquoi la garde de `plateforme/projection/checks.py` est structurellement aveugle
         *     ici — elle ne se déclenche que sur un modèle scopé, donc elle ne dira ni qu'il manque
         *     une portée, ni qu'il n'en faut pas. La garde **positive** vit au plan 04-04, à côté
         *     de `Ordonnance`.
         *
         *     **Pourquoi ce paragraphe ne nomme pas le mixin.** Le plan 04-03 fait de son absence
         *     un critère grepable sur ce fichier ; l'y écrire rendrait le critère rouge sur le
         *     fichier même qui le respecte. C'est la même arbitrage qu'au plan 04-01 avec
         *     `unaccent`, et la même leçon : un critère qui attrape sa propre prose est un critère
         *     mal écrit — il devrait chercher une **ligne d'import** ou une **base de classe**, pas
         *     un mot. Noté pour `04-09`.
         *
         *     Conséquence à ne pas manquer : la portée des lignes de cette ressource est
         *     l'**affaire entière**, et c'est `client.voir` qui en garde la porte. Il n'y a rien à
         *     filtrer dans `get_queryset()` à ce titre.
         *
         *     ## 2. Pas de `DestroyModelMixin`, et `delete` absent de `http_method_names`
         *
         *     Une fiche client se **désactive** (`actif = False`). L'article 211 du CGI impose dix
         *     ans de conservation, et la phase 6 posera un `PROTECT` depuis la facture. `put` est
         *     absent pour la raison de `VueComptes` : un remplacement complet n'a aucun usage ici
         *     et offrirait une seconde porte d'écriture à tenir en cohérence avec la première.
         *
         *     ## 3. Aucun nouveau paramètre de requête, et c'est écrit pour que l'absence se lise
         *
         *     `search` figure **déjà** dans `PARAMETRES_RESERVES`
         *     (`plateforme/projection/filtres.py`), donc `?search=` n'y ajoute rien et le fichier
         *     n'est pas touché par ce plan. Tout autre nom — `?q=`, `?telephone=` — devrait y
         *     entrer **dans le même commit**, sans quoi il produirait le refus unique.
         *     `test_client01_tout_parametre_hors_liste_blanche_est_refuse` vérifie les trois noms
         *     que l'on écrit sans y penser.
         */
        get: operations["clients_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Corriger une fiche client
         * @description La ressource client. **Deux absences délibérées, écrites ici pour être trouvées.**
         *
         *     ## 1. Le mixin de portée magasin est absent, et ce n'est pas un oubli
         *
         *     Un client appartient à l'**affaire**, pas à un point de vente : il achète à Anfa
         *     aujourd'hui et à Maârif dans six mois, et c'est la même personne (décision D-4a). Le
         *     scoper produirait deux fiches pour un humain, donc deux historiques de prescription
         *     pour un seul œil. **Le raisonnement complet, avec sa conséquence clinique, vit dans
         *     la docstring de `clients.Client`** (`domaine/clients/models.py`), qui dit aussi
         *     pourquoi la garde de `plateforme/projection/checks.py` est structurellement aveugle
         *     ici — elle ne se déclenche que sur un modèle scopé, donc elle ne dira ni qu'il manque
         *     une portée, ni qu'il n'en faut pas. La garde **positive** vit au plan 04-04, à côté
         *     de `Ordonnance`.
         *
         *     **Pourquoi ce paragraphe ne nomme pas le mixin.** Le plan 04-03 fait de son absence
         *     un critère grepable sur ce fichier ; l'y écrire rendrait le critère rouge sur le
         *     fichier même qui le respecte. C'est la même arbitrage qu'au plan 04-01 avec
         *     `unaccent`, et la même leçon : un critère qui attrape sa propre prose est un critère
         *     mal écrit — il devrait chercher une **ligne d'import** ou une **base de classe**, pas
         *     un mot. Noté pour `04-09`.
         *
         *     Conséquence à ne pas manquer : la portée des lignes de cette ressource est
         *     l'**affaire entière**, et c'est `client.voir` qui en garde la porte. Il n'y a rien à
         *     filtrer dans `get_queryset()` à ce titre.
         *
         *     ## 2. Pas de `DestroyModelMixin`, et `delete` absent de `http_method_names`
         *
         *     Une fiche client se **désactive** (`actif = False`). L'article 211 du CGI impose dix
         *     ans de conservation, et la phase 6 posera un `PROTECT` depuis la facture. `put` est
         *     absent pour la raison de `VueComptes` : un remplacement complet n'a aucun usage ici
         *     et offrirait une seconde porte d'écriture à tenir en cohérence avec la première.
         *
         *     ## 3. Aucun nouveau paramètre de requête, et c'est écrit pour que l'absence se lise
         *
         *     `search` figure **déjà** dans `PARAMETRES_RESERVES`
         *     (`plateforme/projection/filtres.py`), donc `?search=` n'y ajoute rien et le fichier
         *     n'est pas touché par ce plan. Tout autre nom — `?q=`, `?telephone=` — devrait y
         *     entrer **dans le même commit**, sans quoi il produirait le refus unique.
         *     `test_client01_tout_parametre_hors_liste_blanche_est_refuse` vérifie les trois noms
         *     que l'on écrit sans y penser.
         */
        patch: operations["clients_partial_update"];
        trace?: never;
    };
    "/api/comptes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Les comptes de l'affaire
         * @description `/api/comptes/` — créer un gérant, corriger son identité, le désactiver.
         *
         *     La liste porte ce que `03-UI-SPEC.md` 7.2 affiche, propriétaire compris : sa ligne
         *     est première et marquée, et elle n'ouvre pas d'éditeur de droits (7.7).
         */
        get: operations["comptes_list"];
        put?: never;
        /**
         * Créer un compte gérant
         * @description Le `client` est posé **par le serveur**, et n'est jamais lu dans le corps.
         *
         *     C'est la ligne que la menace T-03-57 vise. Elle est écrite ici, en clair, plutôt
         *     que déduite d'une absence dans un sérialiseur : un lecteur qui cherche « d'où
         *     vient le client de ce compte ? » trouve la réponse au premier endroit où il
         *     regarde.
         */
        post: operations["comptes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comptes/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * La fiche d'un compte
         * @description `/api/comptes/` — créer un gérant, corriger son identité, le désactiver.
         *
         *     La liste porte ce que `03-UI-SPEC.md` 7.2 affiche, propriétaire compris : sa ligne
         *     est première et marquée, et elle n'ouvre pas d'éditeur de droits (7.7).
         */
        get: operations["comptes_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Corriger le nom ou l'adresse d'un compte
         * @description Le nom et l'adresse. Le propriétaire corrige les siens, personne d'autre.
         *
         *     `03-UI-SPEC.md` 7.7 : un gérant-gestionnaire ne modifie pas sa propre fiche — il
         *     ne peut changer que son mot de passe, par `/api/auth/mot-de-passe/`.
         */
        patch: operations["comptes_partial_update"];
        trace?: never;
    };
    "/api/comptes/{id}/droits/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accorder ou retirer un droit
         * @description Un interrupteur : `accorde` décide du sens, `magasins` de la portée.
         *
         *     `magasins` absent vaut **tous les magasins accordés**, ce qui est le
         *     comportement uniforme par défaut de 7.5 et l'état que la quasi-totalité des
         *     affaires verra.
         */
        post: operations["comptes_droits_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comptes/{id}/droits/uniformiser/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Uniformiser un droit sur tous les magasins
         * @description Le bouton `Uniformiser` de 7.5, qui replie une ligne personnalisée.
         *
         *     Une route distincte pour une raison d'interface : l'action demande une
         *     confirmation quand les sous-interrupteurs divergent, et le journal doit pouvoir
         *     se relire comme « il a tout aligné » plutôt que comme une bascule de plus.
         */
        post: operations["comptes_droits_uniformiser_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comptes/{id}/journal/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * L'historique des droits d'un compte
         * @description `03-UI-SPEC.md` 7.3 D — la seule vue de `JournalDroit`, en lecture seule.
         *
         *     Le journal est écrit par le service depuis le plan 03-09 et n'avait pas de route
         *     pour l'alimenter ; celle-ci est la lecture, et rien d'autre. `JournalDroit`
         *     refuse la réécriture et le retrait dans son propre `save()` / `delete()`, donc
         *     « lecture seule » n'est pas une propriété de cette vue — c'est une propriété du
         *     modèle, et cette vue ne pourrait pas la contourner si elle essayait.
         *
         *     **Intersectée comme le reste.** Sans cela, il suffirait d'ouvrir le repli d'un
         *     historique pour apprendre qu'`article.voir_prix_achat` existe et qui le détient,
         *     c'est-à-dire pour contourner en un clic ce que le catalogue et la fiche retirent.
         *
         *     Pas de pagination : l'historique d'un compte est de l'ordre de la dizaine
         *     d'entrées, et un `collapsible` fermé par défaut ne le charge qu'à l'ouverture.
         *     Le jour où une affaire en accumule des milliers, la forme à écrire est une
         *     pagination, pas une troncature silencieuse.
         */
        get: operations["comptes_journal_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comptes/{id}/magasins/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accorder ou retirer l'accès à un magasin
         * @description L'accès à un magasin — le rayon d'action le plus large de cet écran.
         *
         *     Accorder étend les lignes **uniformes** au nouveau magasin et laisse les
         *     personnalisées où elles sont ; retirer emporte les droits qui visaient ce
         *     magasin. Les deux effets sont annoncés par l'interface avant d'être appliqués
         *     (7.5 et 7.9), et appliqués ici que l'interface les ait annoncés ou non.
         *
         *     **L'extension est désormais un choix du propriétaire**, énoncé par l'écran avant
         *     d'être appliqué, et par défaut celui de 7.5. Cette vue ne le prend pas : elle
         *     valide le booléen et le passe au service, où vit toute la logique d'octroi. Le
         *     retrait, lui, ne le reçoit pas — d'où la branche explicite plutôt qu'une table
         *     d'opérations, qui obligerait à passer l'argument à une fonction qui n'en veut pas.
         */
        post: operations["comptes_magasins_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comptes/{id}/mot-de-passe/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Réinitialiser le mot de passe d'un compte
         * @description Un nouveau secret, montré **une seule fois**, et le drapeau reposé.
         *
         *     Changer le mot de passe déconnecte la cible partout : le hachage de session est
         *     dérivé du hachage du mot de passe, donc toute session ouverte devient invalide à
         *     la requête suivante. C'est le comportement voulu pour une réinitialisation, et
         *     c'est pourquoi rien n'est appelé pour purger les sessions à la main.
         */
        post: operations["comptes_mot_de_passe_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comptes/{id}/statut/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activer ou désactiver un compte
         * @description PERM-02 — la désactivation mord dès la requête suivante, sans machinerie.
         *
         *     `ModelBackend.get_user()` appelle `user_can_authenticate()` à **chaque** requête,
         *     donc il n'y a ni liste de révocation ni fenêtre d'expiration à attendre. C'est la
         *     moitié « révocation » de l'argument session-contre-jeton, et le plan 03-08 la
         *     vérifie de bout en bout.
         */
        post: operations["comptes_statut_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comptes/catalogue/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Les droits et les magasins que l'appelant peut accorder
         * @description `GET /api/comptes/catalogue/` — ce que **cet** appelant peut accorder.
         *
         *     Deux catalogues coexistent et répondent à deux questions différentes ; les confondre
         *     serait une régression silencieuse.
         *
         *     | Route | Question | Réponse |
         *     |---|---|---|
         *     | `/api/auth/moi/` | quels droits **existent** ? | les 21, pour tout le monde |
         *     | `/api/comptes/catalogue/` | lesquels **puis-je accorder** ? | l'intersection |
         *
         *     Le premier est identique pour chaque affaire du produit, donc il ne divulgue rien.
         *     Le second dépend de l'appelant, et c'est tout son intérêt : un gérant-gestionnaire
         *     qui ne détient pas `article.voir_prix_achat` n'en voit pas la ligne en éditant un
         *     collègue, **parce qu'elle n'est pas dans la réponse** (`03-UI-SPEC.md` 7.7).
         *
         *     L'intersection est faite **avant** la sérialisation, dans `catalogue_offrable`. Après
         *     serait un filtrage de rendu, et un filtrage de rendu laisse la donnée dans l'objet
         *     qu'il filtre.
         */
        get: operations["comptes_catalogue_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description La forme de `/api/auth/moi/`. **Déclarée pour le schéma, pas pour sérialiser.**
         *
         *     La charge utile est construite par `charge_utile_moi`, qui interroge deux bases et
         *     l'accès résolu ; ce sérialiseur existe pour que `drf-spectacular` produise un
         *     composant et donc un type TypeScript. Sans lui, `AutoSchema` ne devine rien d'une
         *     `APIView` et **ignore la vue entièrement** — les cinq routes d'authentification
         *     seraient absentes du contrat dont le client est généré, ce qui est la pire forme
         *     d'absence : silencieuse et invisible en revue.
         *
         *     `client` est nullable parce qu'un opérateur de plateforme n'appartient à aucune
         *     affaire, et le type généré doit le dire plutôt que promettre un objet.
         */
        Amorcage: {
            readonly utilisateur: components["schemas"]["Utilisateur"];
            readonly client: components["schemas"]["Client"] | null;
            readonly permissions: string[];
            readonly magasins: components["schemas"]["Magasin"][];
            readonly catalogue: components["schemas"]["Catalogue"];
        };
        /**
         * @description `{code, accorde, magasins?}` — un interrupteur, et rien d'autre.
         *
         *     Un seul point de terminaison pour les deux sens, parce que c'est **un seul contrôle**
         *     à l'écran : un `accorde: false` sur une route d'octroi se lit mieux que deux routes
         *     dont l'interface devrait choisir à chaque clic.
         *
         *     `magasins` absent signifie **tous les magasins accordés**, ce qui produit le
         *     comportement uniforme par défaut de 7.5. Le fournir est le chemin « Par magasin »,
         *     celui qui n'apparaît qu'à la demande et seulement au-dessus de deux magasins.
         */
        BasculeDroit: {
            code: components["schemas"]["CodeEnum"];
            accorde: boolean;
            magasins?: string[];
        };
        /**
         * @description `{magasin_code, accorde, reappliquer?}` — l'accès à un magasin (7.3 B).
         *
         *     Le code métier, jamais l'identifiant : c'est ce que stocke `AccesMagasin`, et c'est
         *     ce qui survit à une restauration là où un `id` est réattribué (TENANT-09).
         *
         *     `reappliquer` est le choix que l'écran pose au propriétaire avant d'ajouter un
         *     magasin (contexte de la phase 03.1, décision 2). C'est un champ de **corps** et non
         *     un paramètre de requête : il décide d'une écriture, il voyage donc avec elle, et
         *     `PARAMETRES_RESERVES` n'a pas à le connaître. Facultatif et défaut `True`, pour que
         *     la règle d'aujourd'hui reste la règle pour tout appelant qui ne dit rien.
         */
        BasculeMagasin: {
            magasin_code: string;
            accorde: boolean;
            /**
             * @description À l'ajout d'un magasin : étendre au nouveau magasin les droits accordés uniformément dans tous les autres. Les droits réglés magasin par magasin ne s'étendent jamais, quelle que soit la valeur. Sans effet au retrait.
             * @default true
             */
            reappliquer?: boolean;
        };
        /** @description Le catalogue servi à la SPA : les sections, et la carte des prérequis (7.6). */
        Catalogue: {
            readonly sections: components["schemas"]["SectionCatalogue"][];
            readonly prerequis: {
                [key: string]: string[];
            };
        };
        /**
         * @description La forme de `GET /api/comptes/catalogue/`. Déclarée pour le schéma, pas pour sérialiser.
         *
         *     Le catalogue **complet** est servi par `/api/auth/moi/` via `catalogue_des_droits()` :
         *     il est identique pour chaque affaire du produit, donc il ne divulgue rien, et l'écran
         *     403 de `03-UI-SPEC.md` 8.6 nomme le droit manquant précisément pour cette raison.
         *
         *     Celui-ci répond à une autre question — **ce que l'appelant peut accorder** — et sa
         *     réponse dépend donc de l'appelant. Elle porte en plus les magasins qu'il détient,
         *     parce que l'écran de droits a besoin des deux axes pour dessiner une ligne.
         */
        CatalogueOffrable: {
            readonly sections: components["schemas"]["SectionCatalogue"][];
            readonly prerequis: {
                [key: string]: string[];
            };
            readonly magasins: components["schemas"]["Magasin"][];
        };
        /**
         * @description Le changement par l'intéressé. L'ancien mot de passe est exigé — **sauf** en
         *     changement forcé, et la dérogation s'arrête là.
         *
         *     **Le cas général : `mot_de_passe_actuel` est obligatoire.** Sans lui, un poste laissé
         *     déverrouillé une minute — ou un CSRF réussi — ne donne plus une session mais un
         *     compte, définitivement. C'est la différence entre un incident et une perte de
         *     contrôle, et c'est la garantie que le plan 03-08 a posée ici.
         *
         *     **La dérogation : `doit_changer_mot_de_passe` vrai, et rien d'autre.** Sur
         *     l'atterrissage forcé, la personne vient de saisir ce mot de passe précis, quelques
         *     secondes plus tôt, pour ouvrir la session qui porte cette requête. Le lui redemander
         *     revient à lui faire répéter ce qu'elle vient de taper. Et la garantie ci-dessus ne
         *     protège rien dans cet état : le mot de passe d'un compte en changement forcé a été
         *     **posé par le propriétaire ou par l'opérateur**, il est connu d'un tiers par
         *     construction — c'est précisément pourquoi le drapeau est levé.
         *
         *     Tranché par le propriétaire au point de contrôle du plan 03-13, le 2026-09-17,
         *     revenant sur la décision du point de contrôle 03-12 (`03-UI-SPEC.md` 9.4, amendée
         *     une seconde fois). Deux tests nommés tiennent les deux moitiés, et c'est le second
         *     qui compte : `test_perm01_un_changement_force_n_exige_pas_le_mot_de_passe_actuel` et
         *     `test_perm01_un_compte_ordinaire_reste_refuse_sans_le_mot_de_passe_actuel`. Une
         *     dérogation écrite pour un cas précis s'élargit au premier refactoring qui trouve la
         *     condition gênante ; le second test rougit quand cela arrive.
         *
         *     Facultatif n'est pas ignoré : fourni, le champ est **vérifié**, y compris en
         *     changement forcé — un mot de passe actuel faux reste un 400.
         *
         *     `validate_password` applique `AUTH_PASSWORD_VALIDATORS`, qui est **posé** dans
         *     `config/settings/base.py` : sans validateurs déclarés, cet appel valide `1234` en
         *     silence, et le point de terminaison aurait l'air protégé sans l'être.
         */
        ChangementMotDePasse: {
            /** @description Obligatoire, sauf lorsque le compte porte `doit_changer_mot_de_passe`. */
            mot_de_passe_actuel?: string;
            nouveau_mot_de_passe: string;
        };
        /**
         * @description L'affaire, réduite à ce qui s'affiche.
         *
         *     Deux champs, et la liste est courte pour une raison : la table porte aussi le nom, le
         *     port, l'utilisateur et le mot de passe chiffré de la base de cet opticien. Ajouter
         *     l'un d'eux ici rendrait la suite rouge (voir la docstring du module), ce qui est
         *     exactement l'effet recherché.
         */
        Client: {
            readonly code: string;
            readonly raison_sociale: string;
        };
        /**
         * @description * `client.voir` - Consulter les clients
         *     * `client.modifier` - Créer et modifier des clients
         *     * `ordonnance.voir` - Consulter les ordonnances
         *     * `ordonnance.saisir` - Saisir une ordonnance
         *     * `stock.voir` - Consulter le stock
         *     * `stock.ajuster` - Ajuster le stock / inventaire
         *     * `article.voir_prix_achat` - Voir le prix d'achat
         *     * `vente.voir` - Consulter les ventes et les factures
         *     * `vente.creer` - Enregistrer une vente
         *     * `vente.remise` - Accorder une remise
         *     * `vente.voir_marge` - Voir la marge
         *     * `facture.avoir` - Émettre un avoir
         *     * `caisse.voir` - Consulter la caisse
         *     * `caisse.saisir` - Saisir en caisse
         *     * `caisse.comptage` - Faire le comptage
         *     * `fournisseur.voir` - Consulter les fournisseurs
         *     * `achat.commander` - Passer un bon de commande
         *     * `achat.voir_soldes` - Voir les soldes fournisseurs
         *     * `rappel.voir` - Consulter les rappels
         *     * `dashboard.voir_ca_global` - Voir le CA de toute l'entreprise
         *     * `compte.gerer` - Gérer les comptes et les droits
         * @enum {string}
         */
        CodeEnum: "client.voir" | "client.modifier" | "ordonnance.voir" | "ordonnance.saisir" | "stock.voir" | "stock.ajuster" | "article.voir_prix_achat" | "vente.voir" | "vente.creer" | "vente.remise" | "vente.voir_marge" | "facture.avoir" | "caisse.voir" | "caisse.saisir" | "caisse.comptage" | "fournisseur.voir" | "achat.commander" | "achat.voir_soldes" | "rappel.voir" | "dashboard.voir_ca_global" | "compte.gerer";
        /**
         * @description Une ligne de la liste des comptes et la fiche de détail (`03-UI-SPEC.md` 7.2, 7.3).
         *
         *     Purement sortant : l'écriture passe par `CreationCompteSerializer` et par
         *     `ModificationIdentiteSerializer`, qui ne partagent aucun champ avec celui-ci par
         *     accident.
         *
         *     `nombre_de_droits` et `personnalise` sont calculés **côté serveur**. L'interface ne
         *     doit pas avoir à recomposer l'uniformité d'une ligne depuis N requêtes : à trois
         *     magasins et vingt-et-un codes, le badge « Personnalisé par magasin » coûterait
         *     soixante-trois lectures par ligne de tableau (7.2).
         *
         *     Les noms sont français et les sources sont les colonnes de Django — `actif` pour
         *     `is_active`, `derniere_connexion` pour `last_login`. `test_perm06_tout_champ_de_modele_expose_est_classe`
         *     lit la **source**, pas le nom, donc les deux clés correspondantes sont inscrites dans
         *     `CHAMPS_PUBLICS` et non le nom d'affichage.
         */
        Compte: {
            readonly id: number;
            readonly nom_complet: string;
            /**
             * Adresse e-mail
             * Format: email
             * @description L'identifiant de connexion. Unique sur toute la flotte, donc une adresse e-mail plutôt qu'un nom d'utilisateur : une collision sur « karim » révélerait l'existence du compte d'une autre affaire.
             */
            readonly email: string;
            /**
             * Est propriétaire
             * @description L'opticien qui détient l'affaire. Un seul par client.
             */
            readonly est_proprietaire: boolean;
            readonly actif: boolean;
            /** Doit changer son mot de passe */
            readonly doit_changer_mot_de_passe: boolean;
            /** Format: date-time */
            readonly derniere_connexion: string | null;
            readonly magasins: components["schemas"]["Magasin"][];
            readonly nombre_de_droits: number;
            /** @description Vrai dès qu'un octroi n'est pas uniforme sur les magasins accordés (7.5). */
            readonly personnalise: boolean;
        };
        /**
         * @description La réponse de création et de réinitialisation : le compte, **et le secret, une fois**.
         *
         *     Le mot de passe provisoire ne réapparaît dans aucune autre charge utile. Il n'existe
         *     pas de chemin par courriel (plan 03-08 : aucun fournisseur d'e-mail dans la pile),
         *     donc l'interface l'affiche avec « Notez-le maintenant : il ne sera plus affiché. » et
         *     le propriétaire le transmet de vive voix.
         */
        CompteCree: {
            readonly compte: components["schemas"]["Compte"];
            readonly mot_de_passe_provisoire: string;
        };
        /**
         * @description La fiche (`03-UI-SPEC.md` 7.3), qui porte en plus **l'état de chaque droit**.
         *
         *     Un sérialiseur distinct de celui de la liste, et c'est le point : vingt et un états
         *     par ligne de tableau est précisément le coût que `resume_des_droits` existe pour
         *     éviter (7.2). La liste affiche un nombre et un badge ; la fiche a besoin de chaque
         *     interrupteur, et elle est seule à l'écran.
         *
         *     `droits` et `magasins_accordes` sont **déjà intersectés** avec ce que l'appelant peut
         *     accorder : les codes viennent du même `catalogue_offrable` qui sert le catalogue, et
         *     les magasins de son propre `Acces`. Un état servi pour un code hors catalogue le
         *     réintroduirait par la porte de service, et le grisage que 7.7 refuse serait alors
         *     fait par la SPA faute de mieux.
         */
        CompteDetail: {
            readonly id: number;
            readonly nom_complet: string;
            /**
             * Adresse e-mail
             * Format: email
             * @description L'identifiant de connexion. Unique sur toute la flotte, donc une adresse e-mail plutôt qu'un nom d'utilisateur : une collision sur « karim » révélerait l'existence du compte d'une autre affaire.
             */
            readonly email: string;
            /**
             * Est propriétaire
             * @description L'opticien qui détient l'affaire. Un seul par client.
             */
            readonly est_proprietaire: boolean;
            readonly actif: boolean;
            /** Doit changer son mot de passe */
            readonly doit_changer_mot_de_passe: boolean;
            /** Format: date-time */
            readonly derniere_connexion: string | null;
            readonly magasins: components["schemas"]["Magasin"][];
            readonly nombre_de_droits: number;
            /** @description Vrai dès qu'un octroi n'est pas uniforme sur les magasins accordés (7.5). */
            readonly personnalise: boolean;
            readonly droits: components["schemas"]["LigneDeDroit"][];
            readonly magasins_accordes: string[];
        };
        /**
         * @description Les identifiants soumis. **Aucune validation métier ici, et c'est délibéré.**
         *
         *     Un `validate()` qui appellerait `authenticate()` produirait une `ValidationError`
         *     structurée par champ — `{"email": [...]}` contre `{"mot_de_passe": [...]}` — c'est-à-dire
         *     exactement l'oracle que T-03-48 interdit : la forme du corps dirait lequel des deux
         *     est faux. Le sérialiseur ne vérifie donc que la présence, et la vue rend une réponse
         *     unique.
         *
         *     `trim_whitespace=False` sur le mot de passe : un espace final est un caractère du
         *     secret, et le rogner rendrait indéchiffrable un compte dont le mot de passe en
         *     contient un.
         */
        Connexion: {
            /** Format: email */
            email: string;
            mot_de_passe: string;
        };
        /**
         * @description Le dialogue de création (`03-UI-SPEC.md` 7.2) : trois champs, et pas un de plus.
         *
         *     `client` est posé par la vue depuis `request.acces.client_id` et n'apparaît donc
         *     nulle part ici. Un `ModelSerializer` aurait été plus court et aurait ouvert la porte
         *     à un champ de modèle ajouté plus tard qui deviendrait inscriptible sans que personne
         *     ne le décide : c'est exactement le mode de défaillance de A-03-05.
         *
         *     Le mot de passe provisoire est **facultatif**. Le bouton `Générer un mot de passe` du
         *     dialogue existe précisément pour que le propriétaire n'en invente pas un ; quand il
         *     est absent, le serveur en tire un et le renvoie une seule fois.
         */
        CreationCompte: {
            nom_complet: string;
            /** Format: email */
            email: string;
            mot_de_passe_provisoire?: string;
        };
        /** @description Une ligne de l'écran de droits : le code, son libellé et sa phrase d'explication. */
        DroitCatalogue: {
            readonly code: string;
            readonly libelle: string;
            readonly explication: string;
        };
        /**
         * @description Une ligne de `03-UI-SPEC.md` 7.3 D — la seule vue de `JournalDroit`.
         *
         *     **Déclarée pour le schéma, pas pour sérialiser** : la charge utile est construite par
         *     `charge_utile_journal`, qui joint deux mondes — les libellés des permissions vivent
         *     dans le plan de contrôle, les noms des magasins dans la base de l'opticien.
         *
         *     `nature` plutôt qu'une phrase toute faite. « a accordé « Voir le prix d'achat » » et
         *     « a accordé l'accès au magasin Maârif » ne se composent pas pareil en français, et
         *     cette grammaire-là appartient à l'interface (`03-UI-SPEC.md` 9.3). Le serveur livre
         *     donc un libellé et sa nature, jamais une phrase à afficher telle quelle — une phrase
         *     assemblée ici serait impossible à corriger sans redéployer le serveur.
         */
        EntreeDeJournal: {
            /** Format: date-time */
            readonly le: string;
            readonly action: string;
            readonly nature: string;
            readonly cible: string;
            readonly libelle: string;
            readonly par: string;
        };
        /**
         * @description La personne qui achète : ce qui se saisit, et ce qui s'affiche.
         *
         *     **Les trois colonnes dérivées sont absentes de `fields`, et c'est une décision.**
         *     `nom_recherche`, `cle_phonetique` et `telephone_normalise` sont `editable=False` et
         *     recalculées par `Client.save()` : elles ne sont ni saisies ni servies. Un champ dérivé
         *     qu'un POST pourrait écrire serait une **seconde source de vérité**, et la divergence
         *     serait muette — fiche correcte à l'écran, introuvable à la recherche (T-04-05).
         *
         *     `score` et `raison` ne sont pas des colonnes : ce sont les annotations que
         *     `chercher_clients` pose sur les résultats d'une recherche. Elles sont `null` hors
         *     recherche, et c'est honnête — « cette fiche n'est pas un résultat de recherche » est
         *     une information, pas une absence de droit. Le registre de projection ne les connaît
         *     donc pas, et `test_perm06_tout_champ_de_modele_expose_est_classe` les ignore : il ne
         *     classe que les champs qui sont des colonnes.
         */
        FicheClient: {
            readonly id: number;
            nom: string;
            telephone?: string;
            /** Format: date */
            date_naissance?: string | null;
            adresse?: string;
            notes?: string;
            actif?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /**
             * Format: double
             * @description Le rang du résultat dans la recherche courante, entre 0 et 2. Null hors recherche. **À ne jamais afficher tel quel** : « 0,333 » ne dit rien à un opticien — c'est `raison` qui se montre, en mots.
             */
            readonly score: number | null;
            /** @description Par quelle couche ce résultat a été trouvé : exact, telephone, orthographe, phonetique ou equivalence. Null hors recherche. */
            readonly raison: (components["schemas"]["RaisonEnum"] | components["schemas"]["NullEnum"]) | null;
        };
        /**
         * @description L'état d'un code pour un compte : sa valeur, et les magasins où elle vaut.
         *
         *     `etat` vaut `actif`, `inactif` ou `mixte`. Les deux premiers sont **uniformes** au
         *     sens de 7.5 — tous les magasins accordés sont d'accord — et `mixte` est l'unique
         *     état personnalisé, celui que l'interrupteur parent rend en tri-état avec
         *     `aria-checked="mixed"`.
         */
        LigneDeDroit: {
            readonly code: string;
            readonly etat: string;
            readonly magasins: string[];
        };
        /** @description Un magasin, tel qu'il apparaît dans le sélecteur de la barre supérieure (UI 5.4). */
        Magasin: {
            readonly id: number;
            readonly code: string;
            readonly nom: string;
        };
        /** @enum {unknown} */
        NullEnum: null;
        /**
         * @description La personne qui achète : ce qui se saisit, et ce qui s'affiche.
         *
         *     **Les trois colonnes dérivées sont absentes de `fields`, et c'est une décision.**
         *     `nom_recherche`, `cle_phonetique` et `telephone_normalise` sont `editable=False` et
         *     recalculées par `Client.save()` : elles ne sont ni saisies ni servies. Un champ dérivé
         *     qu'un POST pourrait écrire serait une **seconde source de vérité**, et la divergence
         *     serait muette — fiche correcte à l'écran, introuvable à la recherche (T-04-05).
         *
         *     `score` et `raison` ne sont pas des colonnes : ce sont les annotations que
         *     `chercher_clients` pose sur les résultats d'une recherche. Elles sont `null` hors
         *     recherche, et c'est honnête — « cette fiche n'est pas un résultat de recherche » est
         *     une information, pas une absence de droit. Le registre de projection ne les connaît
         *     donc pas, et `test_perm06_tout_champ_de_modele_expose_est_classe` les ignore : il ne
         *     classe que les champs qui sont des colonnes.
         */
        PatchedFicheClient: {
            readonly id?: number;
            nom?: string;
            telephone?: string;
            /** Format: date */
            date_naissance?: string | null;
            adresse?: string;
            notes?: string;
            actif?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
            /**
             * Format: double
             * @description Le rang du résultat dans la recherche courante, entre 0 et 2. Null hors recherche. **À ne jamais afficher tel quel** : « 0,333 » ne dit rien à un opticien — c'est `raison` qui se montre, en mots.
             */
            readonly score?: number | null;
            /** @description Par quelle couche ce résultat a été trouvé : exact, telephone, orthographe, phonetique ou equivalence. Null hors recherche. */
            readonly raison?: (components["schemas"]["RaisonEnum"] | components["schemas"]["NullEnum"]) | null;
        };
        /**
         * @description `PATCH` sur la fiche : le nom et l'adresse, rien d'autre (`03-UI-SPEC.md` 7.3 A).
         *
         *     Le statut n'est pas ici, et c'est la spécification : `Statut` est une liste
         *     déroulante suivie d'une confirmation, pas un interrupteur, parce que la
         *     désactivation mérite d'être confirmée. Elle a donc son propre point de terminaison,
         *     ce qui la rend aussi identifiable côté serveur.
         */
        PatchedModificationIdentite: {
            nom_complet?: string;
            /** Format: email */
            email?: string;
        };
        /** @enum {string} */
        RaisonEnum: "exact" | "telephone" | "orthographe" | "phonetique" | "equivalence";
        /**
         * @description Ce qu'une bascule renvoie, et ce que l'écran de droits en fait.
         *
         *     | Champ | Ce que l'interface en fait |
         *     |---|---|
         *     | `lignes` | redessine chaque interrupteur touché, **sans recharger** (7.8) |
         *     | `cascade` | la note en ligne « … a été activé automatiquement » (7.6) |
         *     | `cascade` | et le **toast d'annulation unique** qui couvre tout l'ensemble |
         *     | `magasins_accordes` | le dénominateur de « Personnalisé : 2 magasins sur 3 » |
         *     | `magasins_etendus` | la note « Californie a été ajouté. Vérifiez les 2 droits… » |
         *
         *     `lignes` porte le code demandé **en tête**, puis les codes emportés par la cascade.
         */
        ResultatOctroi: {
            readonly code: string;
            readonly action: string;
            readonly lignes: components["schemas"]["LigneDeDroit"][];
            readonly cascade: string[];
            readonly magasins_accordes: string[];
            readonly magasins_etendus: string[];
        };
        /** @description Un bloc de l'écran de droits, dans l'ordre d'affichage (`03-UI-SPEC.md` 7.4). */
        SectionCatalogue: {
            readonly titre: string;
            readonly droits: components["schemas"]["DroitCatalogue"][];
        };
        /**
         * @description `{"actif": false}` — la désactivation, et son inverse (`03-UI-SPEC.md` 7.9).
         *
         *     Une action explicite plutôt qu'un `PATCH` sur `is_active` : côté interface elle
         *     mérite une confirmation, et côté serveur elle mérite d'être un événement
         *     identifiable plutôt qu'une colonne parmi d'autres dans un corps partiel.
         */
        Statut: {
            actif: boolean;
        };
        /** @description `{code, accorde}` — le bouton `Uniformiser` de 7.5, qui replie une ligne mixte. */
        Uniformisation: {
            code: components["schemas"]["CodeEnum"];
            accorde: boolean;
        };
        /**
         * @description Le compte connecté, tel que la SPA le lit.
         *
         *     `doit_changer_mot_de_passe` est dans la charge utile parce que la SPA en a besoin
         *     pour router vers `/mot-de-passe` avant d'afficher quoi que ce soit d'autre
         *     (`03-UI-SPEC.md` 6). `est_proprietaire` y est parce que c'est lui qui décide quelles
         *     surfaces d'administration sont proposées (7.7) — proposées, jamais autorisées : le
         *     serveur reste seul juge, et `Acces` est déjà matérialisé sans branche de privilège.
         */
        Utilisateur: {
            readonly id: number;
            /**
             * Adresse e-mail
             * Format: email
             * @description L'identifiant de connexion. Unique sur toute la flotte, donc une adresse e-mail plutôt qu'un nom d'utilisateur : une collision sur « karim » révélerait l'existence du compte d'une autre affaire.
             */
            readonly email: string;
            readonly nom_complet: string;
            /**
             * Est propriétaire
             * @description L'opticien qui détient l'affaire. Un seul par client.
             */
            readonly est_proprietaire: boolean;
            /** Doit changer son mot de passe */
            readonly doit_changer_mot_de_passe: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_connexion_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Connexion"];
                "application/x-www-form-urlencoded": components["schemas"]["Connexion"];
                "multipart/form-data": components["schemas"]["Connexion"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amorcage"];
                };
            };
        };
    };
    auth_csrf_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_deconnexion_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_moi_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amorcage"];
                };
            };
        };
    };
    auth_mot_de_passe_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangementMotDePasse"];
                "application/x-www-form-urlencoded": components["schemas"]["ChangementMotDePasse"];
                "multipart/form-data": components["schemas"]["ChangementMotDePasse"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amorcage"];
                };
            };
        };
    };
    clients_list: {
        parameters: {
            query?: {
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
                /** @description Le terme brut saisi au comptoir — nom ou téléphone, dans n'importe quelle graphie et n'importe quelle écriture. Il est normalisé **par le serveur** : ne rien retirer, ne rien plier et ne rien filtrer côté client. Sous deux caractères, rien n'est cherché. Au plus 20 candidats sont rendus, chacun portant `score` et `raison`. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FicheClient"][];
                };
            };
        };
    };
    clients_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FicheClient"];
                "application/x-www-form-urlencoded": components["schemas"]["FicheClient"];
                "multipart/form-data": components["schemas"]["FicheClient"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FicheClient"];
                };
            };
        };
    };
    clients_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) client. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FicheClient"];
                };
            };
        };
    };
    clients_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) client. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedFicheClient"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedFicheClient"];
                "multipart/form-data": components["schemas"]["PatchedFicheClient"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FicheClient"];
                };
            };
        };
    };
    comptes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Compte"][];
                };
            };
        };
    };
    comptes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreationCompte"];
                "application/x-www-form-urlencoded": components["schemas"]["CreationCompte"];
                "multipart/form-data": components["schemas"]["CreationCompte"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompteCree"];
                };
            };
        };
    };
    comptes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) utilisateur. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompteDetail"];
                };
            };
        };
    };
    comptes_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) utilisateur. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedModificationIdentite"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedModificationIdentite"];
                "multipart/form-data": components["schemas"]["PatchedModificationIdentite"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Compte"];
                };
            };
        };
    };
    comptes_droits_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) utilisateur. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BasculeDroit"];
                "application/x-www-form-urlencoded": components["schemas"]["BasculeDroit"];
                "multipart/form-data": components["schemas"]["BasculeDroit"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultatOctroi"];
                };
            };
        };
    };
    comptes_droits_uniformiser_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) utilisateur. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Uniformisation"];
                "application/x-www-form-urlencoded": components["schemas"]["Uniformisation"];
                "multipart/form-data": components["schemas"]["Uniformisation"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultatOctroi"];
                };
            };
        };
    };
    comptes_journal_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) utilisateur. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntreeDeJournal"][];
                };
            };
        };
    };
    comptes_magasins_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) utilisateur. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BasculeMagasin"];
                "application/x-www-form-urlencoded": components["schemas"]["BasculeMagasin"];
                "multipart/form-data": components["schemas"]["BasculeMagasin"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultatOctroi"];
                };
            };
        };
    };
    comptes_mot_de_passe_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) utilisateur. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompteCree"];
                };
            };
        };
    };
    comptes_statut_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) utilisateur. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Statut"];
                "application/x-www-form-urlencoded": components["schemas"]["Statut"];
                "multipart/form-data": components["schemas"]["Statut"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Compte"];
                };
            };
        };
    };
    comptes_catalogue_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogueOffrable"];
                };
            };
        };
    };
}
