# Generated by Django 6.1.1 on 2026-09-14 14:31

import django.db.models.deletion
import plateforme.comptes.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control_plane', '0003_backuprun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(help_text="L'identifiant de connexion. Unique sur toute la flotte, donc une adresse e-mail plutôt qu'un nom d'utilisateur : une collision sur « karim » révélerait l'existence du compte d'une autre affaire.", max_length=254, unique=True, verbose_name='adresse e-mail')),
                ('nom_complet', models.CharField(max_length=150, verbose_name='nom complet')),
                ('est_proprietaire', models.BooleanField(default=False, help_text="L'opticien qui détient l'affaire. Un seul par client.", verbose_name='est propriétaire')),
                ('is_active', models.BooleanField(default=True, help_text='Décoché, le compte est refusé dès la requête suivante : ModelBackend.get_user appelle user_can_authenticate à chaque requête, donc la désactivation (PERM-02) ne demande aucune machinerie de révocation.', verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False, help_text="Accès à l'admin de flotte. Impossible pour un compte rattaché à un client.", verbose_name='opérateur')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='super-opérateur')),
                ('doit_changer_mot_de_passe', models.BooleanField(default=False, verbose_name='doit changer son mot de passe')),
                ('derniere_connexion_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de dernière connexion')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('client', models.ForeignKey(blank=True, help_text="Vide pour un opérateur de la plateforme, qui n'appartient à aucune affaire.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='control_plane.client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['email'],
                'constraints': [models.CheckConstraint(condition=models.Q(('client__isnull', True), models.Q(('is_staff', False), ('is_superuser', False)), _connector='OR'), name='un_utilisateur_client_n_est_jamais_operateur', violation_error_message="Un compte rattaché à un client ne peut pas être opérateur. L'admin Django est la gestion de flotte — il expose le nom, l'hôte et les identifiants de la base de chaque opticien — pas les données d'un opticien."), models.CheckConstraint(condition=models.Q(('client__isnull', False), ('est_proprietaire', False), _connector='OR'), name='un_proprietaire_appartient_a_un_client', violation_error_message="Un propriétaire sans client est un titre sans périmètre : il n'y a aucune affaire dont il serait le propriétaire."), models.UniqueConstraint(condition=models.Q(('est_proprietaire', True)), fields=('client',), name='un_seul_proprietaire_par_client', violation_error_message='Cette affaire a déjà un propriétaire. Les comptes supplémentaires sont des gérants, avec des droits accordés un par un.')],
            },
            managers=[
                ('objects', plateforme.comptes.managers.UtilisateurManager()),
            ],
        ),
    ]
