# Generated by Django 6.1.1 on 2026-09-14 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesMagasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magasin_code', models.CharField(help_text="Le code métier du magasin, tel qu'il existe dans la base de l'opticien. Une valeur, pas une relation : la base du client et le plan de contrôle sont deux connexions distinctes.", max_length=20, verbose_name='code du magasin')),
                ('accorde_le', models.DateTimeField(auto_now_add=True, verbose_name='accordé le')),
                ('accorde_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='accordé par')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_magasins', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'accès à un magasin',
                'verbose_name_plural': 'accès aux magasins',
                'ordering': ['utilisateur', 'magasin_code'],
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'magasin_code'), name='uniq_acces_magasin_par_utilisateur', violation_error_message="Ce compte a déjà accès à ce magasin. L'accès est une ligne, pas un compteur.")],
            },
        ),
        migrations.CreateModel(
            name='DroitAccorde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magasin_code', models.CharField(help_text="Le magasin dans lequel ce droit s'applique. Un droit accordé à Anfa ne vaut rien à Maârif — c'est toute la raison d'être de cette colonne.", max_length=20, verbose_name='code du magasin')),
                ('code', models.CharField(choices=[('client.voir', 'Consulter les clients'), ('client.modifier', 'Créer et modifier des clients'), ('ordonnance.voir', 'Consulter les ordonnances'), ('ordonnance.saisir', 'Saisir une ordonnance'), ('stock.voir', 'Consulter le stock'), ('stock.ajuster', 'Ajuster le stock / inventaire'), ('article.voir_prix_achat', "Voir le prix d'achat"), ('vente.voir', 'Consulter les ventes et les factures'), ('vente.creer', 'Enregistrer une vente'), ('vente.remise', 'Accorder une remise'), ('vente.voir_marge', 'Voir la marge'), ('facture.avoir', 'Émettre un avoir'), ('caisse.voir', 'Consulter la caisse'), ('caisse.saisir', 'Saisir en caisse'), ('caisse.comptage', 'Faire le comptage'), ('fournisseur.voir', 'Consulter les fournisseurs'), ('achat.commander', 'Passer un bon de commande'), ('achat.voir_soldes', 'Voir les soldes fournisseurs'), ('rappel.voir', 'Consulter les rappels'), ('dashboard.voir_ca_global', "Voir le CA de toute l'entreprise"), ('compte.gerer', 'Gérer les comptes et les droits')], help_text='Un code du catalogue, jamais une permission Django.', max_length=64, verbose_name='permission')),
                ('accorde_le', models.DateTimeField(auto_now_add=True, verbose_name='accordé le')),
                ('accorde_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='accordé par')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='droits', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'droit accordé',
                'verbose_name_plural': 'droits accordés',
                'ordering': ['utilisateur', 'magasin_code', 'code'],
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'magasin_code', 'code'), name='uniq_droit_par_utilisateur_magasin_code', violation_error_message='Ce droit est déjà accordé à ce compte pour ce magasin. Les trois colonnes sont dans la contrainte : la même permission peut être accordée dans un magasin et refusée dans un autre (CLAUDE.md #13).')],
            },
        ),
        migrations.CreateModel(
            name='JournalDroit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('accorde', 'Accordé'), ('revoque', 'Révoqué')], max_length=8, verbose_name='action')),
                ('cible', models.CharField(help_text='Un code de permission ou un code de magasin. Une valeur, pas une clé.', max_length=64, verbose_name='cible')),
                ('le', models.DateTimeField(auto_now_add=True, verbose_name='le')),
                ('par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='par')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur concerné')),
            ],
            options={
                'verbose_name': 'entrée de journal des droits',
                'verbose_name_plural': 'journal des droits',
                'ordering': ['-le'],
                'indexes': [models.Index(fields=['utilisateur', '-le'], name='idx_journal_utilisateur')],
            },
        ),
    ]
