# Generated by Django 6.1.1 on 2026-09-13 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('magasins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_article', models.CharField(db_index=True, max_length=64)),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('ajustement', 'Ajustement'), ('inventaire', 'Inventaire')], max_length=16)),
                ('quantite_delta', models.IntegerField()),
                ('motif', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='magasins.magasin')),
            ],
            options={
                'verbose_name': 'mouvement de stock',
                'verbose_name_plural': 'mouvements de stock',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['magasin', 'reference_article', 'created_at'], name='idx_mvt_magasin_ref_date')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantite_delta', 0), _negated=True), name='mouvement_stock_delta_non_nul', violation_error_message='A stock movement of zero moves nothing. It is either a mistake or a row that should not exist; either way the ledger must not carry it.')],
            },
        ),
    ]
