# Generated by Django 6.1.1 on 2026-09-18 20:03

import domaine.ordonnances.stockage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordonnances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='photo',
            field=models.FileField(blank=True, editable=False, max_length=120, null=True, storage=domaine.ordonnances.stockage.stockage_des_photos, upload_to=''),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='photo_attachee_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='photo_octets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='photo_par',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='photo_type',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
