# Generated by Django 6.1.1 on 2026-09-13 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('magasins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcritureCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sens', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=8)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('libelle', models.CharField(max_length=200)),
                ('effet_sur_solde', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='magasins.magasin')),
            ],
            options={
                'verbose_name': 'écriture de caisse',
                'verbose_name_plural': 'écritures de caisse',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['magasin', 'created_at'], name='idx_ecr_magasin_date')],
                'constraints': [models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='ecriture_caisse_montant_positif', violation_error_message="An écriture's montant is always positive; direction is `sens`. A signed amount makes a sign error indistinguishable from a refund.")],
            },
        ),
    ]
